name = "majestikmagikcom"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
dir = ".vercel/output/static"